### ISSUE TITLE
Helm templates

### ISSUE THREAD

**Issue by juuben** [NordicWayInterchange/interchange#34]
Hi,

I noticed that when using Helm configuration templates for creating interchange deployment, no messages where delivered. I made following change to qpid-config.yml for make messaging to work for user queue.

               "arguments": {
                 "x-filter-jms-selector": "{{ .binding }}"
               },
-              "bindingKey": "binding_key",
+              "bindingKey": "where1",

Should 'binding_key' be templating variable or was there some thing I missed?

**Comment by RogerMartinsen** [comment]
The bindingKey name should not make a difference.  Which version of message broker are you using?

**Comment by juuben** [comment]
Version: 7.0.6

**Comment by RogerMartinsen** [comment]
7.0.6 broker-j is the same version we use.

I have not tested the qpid-config.yml file, but I have tested the interchangenode/src/test/java/no/vegvesen/ixn/QpidIT.java that uses the interchangenode/src/test/resources/qpid/localhost.json qpid-config-file. Isolated tests here show that bindingKey name "binding_key" is tolerated, and the tests run fine verifying the routing of messages.

I will look more into the Helm soon if needed.

**Comment by ida-berge** [comment]
Hi @juuben! 

We defined the helm values in a separate file, not in the public repo. 

For the `qpid-config.yml` variables, like: 
```yaml
"durableBindings": [
            {{- range .Values.qpid.users }}                 # Loops over all the users
            {
              "arguments": {
                "x-filter-jms-selector": "{{ .binding }}"   #  sets the user's binding
              },
              "bindingKey": "binding_key",
              "destination": "{{ .name }}"                  # Sets the destination queue:  the name of the user queue is the user's name
            },
            {{- end }}
```

we defined the binding in the values-file in the following way: 
```yaml
qpid:
  users:
    - name: king_harald
      binding: "where='NO'"
```

If you are interested in looking at two different examples of our values-files, for the basic interchange and for the federated interchange, check out our wiki page on deploying to the cloud: 
[Deploying the Interchange Node: a step-by-step guide](https://github.com/NordicWayInterchange/interchange/wiki/Deploying-the-Interchange-Node:-a-step-by-step-guide)
